config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :steps
  devise_for :users, controllers:{
      sessions: 'users/sessions'
  }
  resources :portfolios
  resources :blogs
  resources :sites
  scope '/cabinet' do
    resources :messages, :orders
  end
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'page/index'
  root 'page#index'
  match '/contact', to: 'page#contact', via: [:get]
  match '/service', to: 'service#index', via: [:get]
  match '/service', to: 'service#create', via: [:post]
  match '/service/site', to: 'service#site', via: [:get]
  match '/service/dizajn', to: 'service#dizajn', via: [:get]
  match '/service/mobile', to: 'service#mobile', via: [:get]
  match '/service/business', to: 'service#business', via: [:get]
  resources :blog, :case
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_attached_file :image, styles: { large: "1920x1280", small: "300x200"}, default_url: "/images/:style/missing.png"
  validates :name, presence: true
  validates :tag, presence: true
  validates :annotation, presence: true,length: {maximum:290}
  validates :description, presence: true
  validates_attachment :image, presence: true,
                       content_type: { content_type: ["image/jpeg", "image/png", "image/jpg"] },
                       size: { in: 0..2.megabytes }
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :order
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :messages
  has_many :steps
  has_many :documents
  validates :user_name, presence: true
  validates :user_email, presence: true
  validates :user_phone, presence: true
  validates :user_password, confirmation: true
  validates :user_password_confirmation, presence: true
  validates :user_name, presence: true

end

app/models/page.rb
class Page < ApplicationRecord
  #attr_accessible :page_title, :description, :keywords
 #validates :page_title, :description, :keywords
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_attached_file :image, styles: { large: "1920x1280", small: "330x650"}, default_url: "/images/:style/missing.png"
  validates :title, presence: true
  validates :tag, presence: true
  validates :annotation, presence: true
  validates_attachment :image, presence: true,
                       content_type: { content_type: ["image/jpeg", "image/png", "image/jpg"] },
                       size: { in: 0..2.megabytes }
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/site.rb
class Site < ApplicationRecord
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable and :omniauthable
  has_many :orders, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
        flash[:success] = "Емае, кейсик создан, Мих если это ты то красавчик Ваааще"

      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
        flash.now[:error] = "Мих ну ты че, ну нормально все проверь и отправь снова"

      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :tag, :annotation, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Модуль создания переменных экземпляра для динамического отображения названий страниц
    def meta_title_for(title, site)
      return site if title.blank?
      title.include?(site) ? title : "#{title} — #{site}"
    end

  end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/blogs/_filtr.html.erb
<ul class="filt">
  <li><a href="#" class="active">Все</a></li>
  <li><a href="#">Дизайн</a></li>
  <li><a href="#">Веб-разработка</a></li>
  <li><a href="#">Мобильные приложения</a></li>
  <li><a href="#">CRM</a></li>
</ul>

app/views/blogs/_form.html.erb
<style> form #blog_name, form #blog_annotation {
  border: 1px solid #1faee2;
  border-radius: 5px;
  font-size: 1rem;
  width: 100%;
  padding: 10px;
}
form input{
  font-size:1rem;
  padding: 10px;
}
form .btn {
  background: #1faae2;
  btn: white;
  border-radius:5px;
}</style>

<br>
<br>
<br>
<div class="wrap">
  <%= simple_form_for(@blog) do |f| %>
    <%= f.error_notification %>
    <%= f.label :name, ("Название статьи") %><br>
    <%= f.input :name %>
    <br>
    <br>
    <%= f.label :annotation, ("Краткое описание")%><br>
    <%= f.input :annotation %>
    <br>
    <br>
    <%= f.label :tag, ("Выбор категории") %>
    <br>
    <%= f.input_field :tag, :collection => { 'Дизайн' => 1, 'Разработка сайта' => 2, 'CRM' => 3, 'Мобильные приложения' => 4}; %>
    <br>
    <br>
    <%= f.input :description, as: :text, input_html: {class:'ckeditor'} %>
    <%= f.input :image, as: :file %>
    <div class="form-actions">
    <%= f.button :submit %>
    </div>
    <br>
    <br>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<%
  meta title: "Корпоративный блог",
       description: "В информационном блоге специалисты нашей компании размещают полезную для клиентов информацию, связанную с нашей деятельностью.",
       keywords: "Дизайн, Веб разработка" "Мобильные приложения" "CRM системы"
%>

<main class="page">
  <div class="screen for_screen" id="screen5">
    <h1>БЛОГ</h1>
  </div>
  <div class="screen filtr wrap mediafont">
    <%=render 'filtr' %>
    <div class="blogs_wrap">
      <% @blogs.each do |blog| %>
        <div class="blogs_wrap__item">
          <%= image_tag blog.image.url(:large) %>
          <div class="blogs_wrap__item_dos">
            <p><%=  blog.created_at.strftime("%d.%m.%Y") %></p>
            <h3><%= blog.name %></h3>
            <p><%= blog.annotation %></p>
            <%= link_to 'ПОДРОБНЕЕ', blog %>
          </div>
        </div>
      <% end %>
      <div class="blogs_wrap__item">
        <%= image_tag "blogitem.jpeg" %>
        <div class="blogs_wrap__item_dos">
          <p>22.05.1997</p>
          <h3>Гульмен разгулялся в безысходных скитания мэддисона</h3>
          <p>
            Lorem Ipsum - это текст-"рыба", часто используемый в печати и
            вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для
            текстов на латинице с начала XVI века. В то время некий
            безымянный печатник создал большую коллекцию размеров
            и форм шрифтов, используя Lorem Ipsum для распечатки
          </p>
          <a href="#">ПОДРОБНЕЕ</a>
        </div>
      </div>
      <div class="blogs_wrap__item">
        <%= image_tag "blogitem.jpeg" %>
        <div class="blogs_wrap__item_dos">
          <p>22.05.1997</p>
          <h3>Гульмен разгулялся в безысходных скитания мэддисона</h3>
          <p>
            Lorem Ipsum - это текст-"рыба", часто используемый в печати и
            вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для
            текстов на латинице с начала XVI века. В то время некий
            безымянный печатник создал большую коллекцию размеров
            и форм шрифтов, используя Lorem Ipsum для распечатки
          </p>
          <a href="#">ПОДРОБНЕЕ</a>
        </div>
      </div>
      <div class="blogs_wrap__item">
        <%= image_tag "blogitem.jpeg" %>
        <div class="blogs_wrap__item_dos">
          <p>22.05.1997</p>
          <h3>Гульмен разгулялся в безысходных скитания мэддисона</h3>
          <p>c
            Lorem Ipsum - это текст-"рыба", часто используемый в печати и
            вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для
            текстов на латинице с начала XVI века. В то время некий
            безымянный печатник создал большую коллекцию размеров
            и форм шрифтов, используя Lorem Ipsum для распечатки
          </p>
          <a href="#">ПОДРОБНЕЕ</a>
        </div>
      </div>
    </div>
  </div>

  <%= render 'layouts/contactform'%>


</main>
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<main class="page">
  <div class="screen for_screen" id="screen3">
    <h1>БЛОГ</h1>
  </div>
  <div class="screen filtr wrap">
    <%= render 'filtr'%>
    <div class="blog_contant">
      <div class="left_blog">
        <h3><%= @blog.name%></h3>
        <p class="data"><%=@blog.created_at%></p>
        <!--<div class="blog_soclinks">-->
        <!--<a href="#"><img src="img/twiter1.png"> </a>-->
        <!--<a href="#"><img src="img/facebook1.png"></a>-->
        <!--<a href="#"><img src="img/google1.png"></a>-->
        <!--<a href="#"><img src="img/vk1.png"></a>-->
        <!--</div>-->
        <p id="notice"><%= notice %></p>

        <%= raw @blog.description%>
        <%= image_tag @blog.image.url(:large), class: 'blog_left_img' %>
      </div>
      <div class="right_blog">
        <!--<div class="regiser">-->
        <!--<h3>Автор</h3>-->
        <!--<img src="img/unit/wool.png" alt="">-->
        <!--<p class="regiser_name">Козырь Денис</p>-->
        <!--<p class="regiser_rang">Арт-директор</p>-->
        <!--</div>-->
        <!--<h3 class="title_blog">Рекомендуем:</h3>-->
        <!--<a href="#" class="blog_name">-->
        <!--<img src="img/blogitem.jpeg" alt="">-->
        <!--<p>Название еще одного супер уникального блога</p>-->
        <!--</a>-->
        <!--<a href="#" class="blog_name">-->
        <!--<img src="img/blogitem.jpeg" alt="">-->
        <!--<p>Название еще одного супер уникального блога</p>-->
        <!--</a>-->
        <!--<a href="#" class="blog_name">-->
        <!--<img src="img/blogitem.jpeg" alt="">-->
        <!--<p>Название еще одного супер уникального блога</p>-->
        <!--</a>-->
      </div>
    </div>
  </div>
</main>