config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :steps
  devise_for :users, controllers:{
      sessions: 'users/sessions'
  }
  resources :portfolios
  resources :blogs
  resources :sites
  scope '/cabinet' do
    resources :messages, :orders
  end
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'page/index'
  root 'page#index'
  match '/contact', to: 'page#contact', via: [:get]
  match '/service', to: 'service#index', via: [:get]
  match '/service', to: 'service#create', via: [:post]
  match '/service/site', to: 'service#site', via: [:get]
  match '/service/dizajn', to: 'service#dizajn', via: [:get]
  match '/service/mobile', to: 'service#mobile', via: [:get]
  match '/service/business', to: 'service#business', via: [:get]
  resources :blog, :case
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_attached_file :image, styles: { large: "1920x1280", small: "300x200"}, default_url: "/images/:style/missing.png"
  validates :name, presence: true
  validates :tag, presence: true
  validates :annotation, presence: true,length: {maximum:290}
  validates :description, presence: true
  validates_attachment :image, presence: true,
                       content_type: { content_type: ["image/jpeg", "image/png", "image/jpg"] },
                       size: { in: 0..2.megabytes }
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :order
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :messages
  has_many :steps
  has_many :documents
  validates :user_name, presence: true
  validates :user_email, presence: true
  validates :user_phone, presence: true
  validates :user_password, confirmation: true
  validates :user_password_confirmation, presence: true
  validates :user_name, presence: true

end

app/models/page.rb
class Page < ApplicationRecord
  #attr_accessible :page_title, :description, :keywords
 #validates :page_title, :description, :keywords
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_attached_file :image, styles: { large: "1920x1280", small: "330x650"}, default_url: "/images/:style/missing.png"
  validates :title, presence: true
  validates :tag, presence: true
  validates :annotation, presence: true
  validates_attachment :image, presence: true,
                       content_type: { content_type: ["image/jpeg", "image/png", "image/jpg"] },
                       size: { in: 0..2.megabytes }
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/site.rb
class Site < ApplicationRecord
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable and :omniauthable
  has_many :orders, dependent: :destroy
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:title, :tag, :annotation, :image )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Модуль создания переменных экземпляра для динамического отображения названий страниц
    def meta_title_for(title, site)
      return site if title.blank?
      title.include?(site) ? title : "#{title} — #{site}"
    end

  end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/portfolios/_filtr.html.erb
<ul class="filt">
  <li><a href="#" class="active">Все</a></li>
  <li><a href="#">Логотипы</a></li>
  <li><a href="#">Сайты</a></li>
  <li><a href="#">баннера</a></li>
</ul>

app/views/portfolios/_form.html.erb
<style> form #portfolio_title {
  border: 1px solid #1faee2;
  border-radius: 5px;
  font-size: 1rem;
  width: 100%;
  padding: 10px;
}
form input{
  font-size:1rem;
  padding: 10px;
}
form .btn {
  background: #1faae2;
  btn: white;
  border-radius:5px;
}</style>
<br><br><br>
<div class="wrap">
<%= simple_form_for(@portfolio) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <br>
    <%= f.label :tag, ("Выбор типа") %>
    <%= f.input_field :tag, :collection => { 'Логотипы' => 1, 'Сайты' => 2, 'Баннера' => 3}; %>
    <br>
    <br>
    <%= f.input :annotation, as: :text, input_html: {class:'ckeditor'}%>
    <br>
    <%= f.input :image, as: :file %> <br>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<main class="page">
  <div class="screen for_screen" id="screen3">
    <h1>ПОРТФОЛИО</h1>
  </div>
  <div class="screen filtr wrap">
    <%= render 'filtr' %>
    <div class="filtr_wrap ">
      <% @portfolios.each do |portfolio| %>
        <style>#filtr_item<%="#{portfolio.id}" %>{
          background-image: url("<%=portfolio.image.url(:small)%>");
        }</style>
        <%= link_to  portfolio, class: "filtr_item", id: "filtr_item#{portfolio.id}" do %>

        <%= image_tag 'ojo.png'%>
        <%= content_tag(:span, "#{portfolio.title}") %>
          <% end %>
      <% end %>
    <a href="#" class="filtr_item" id="filtr_item1">
        <img src="img/ojo.png" alt="">
        <span>
                     Доготип того-то тогото
                  </span>
      </a>
      <a href="#" class="filtr_item" id="filtr_item2">
        <img src="img/ojo.png" alt="">
        <span>
                     Доготип того-то тогото
                  </span>
      </a>
      <a href="#" class="filtr_item" id="filtr_item3">
        <img src="img/ojo.png" alt="">
        <span>
                     Доготип того-то тогото
                  </span>
      </a>
      <a href="#" class="filtr_item" id="filtr_item4">
        <img src="img/ojo.png" alt="">
        <span>
                     Доготип того-то тогото
                  </span>
      </a>
      <a href="#" class="filtr_item" id="filtr_item5">
        <img src="img/ojo.png" alt="">
        <span>
                     Доготип того-то тогото
                  </span>
      </a>
      <a href="#" class="filtr_item" id="filtr_item6">
        <img src="img/ojo.png" alt="">
        <span>
                     Доготип того-то тогото
                  </span>
      </a>
      <a href="#" class="filtr_item" id="filtr_item7">
        <img src="img/ojo.png" alt="">
        <span>
                     Доготип того-то тогото
                  </span>
      </a>
      <a href="#" class="filtr_item" id="filtr_item8">
        <img src="img/ojo.png" alt="">
        <span>
                     Доготип того-то тогото
                  </span>
      </a>
      <a href="#" class="filtr_item" id="filtr_item9">
        <img src="img/ojo.png" alt="">
        <span>
                     Доготип того-то тогото
                  </span>
      </a>
    </div>
  </div>
  <div class="screen" id="screen_forma">
    <h2>Обратная связь</h2>
    <div class="wrap">
      <form action="#" class="form">
        <input type="text" placeholder="Дурашка">
        <input type="tel" placeholder="Телефон">
        <input type="email" placeholder="E-mail">
        <textarea>Суть вопроса...</textarea>
        <button type="submit">Отправить запрос</button>
      </form>
    </div>
  </div>

</main>
<p id="notice"><%= notice %></p>

<h1>Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.title %></td>
        <td><%= portfolio.tag %></td>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<main class="page">
  <div class="screen for_screen" id="screen3">
    <h1>ПОРТФОЛИО</h1>
  </div>
  <div class="screen filtr wrap">
    <%= render 'filtr'%>
    <div class="info_item">
      <img src="#" alt="" class="mr20">
      <div class="info_text">
        <h3>Что такое Lorem Ipsum?</h3>
        <p>
          Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без заметных изменений пять веков, но и перешагнул в электронный дизайн. Его популяризации в новое время послужили публикация листов Letraset с образцами Lorem Ipsum в 60-х годах и, в более недавнее время, программы электронной вёрстки типа Aldus PageMaker, в шаблонах которых используется Lorem Ipsum.
        </p>
      </div>
    </div>
    <div class="info_item">

      <div class="info_text mr20">
        <h3>Что такое Lorem Ipsum?</h3>
        <p>
          Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без заметных изменений пять веков, но и перешагнул в электронный дизайн. Его популяризации в новое время послужили публикация листов Letraset с образцами Lorem Ipsum в 60-х годах и, в более недавнее время, программы электронной вёрстки типа Aldus PageMaker, в шаблонах которых используется Lorem Ipsum.
        </p>
      </div>
      <img src="#" alt="" >
    </div>
    <div class="info_item">
      <img src="#" alt="" class="mr20">
      <div class="info_text">
        <h3>Что такое Lorem Ipsum?</h3>
        <p>
          Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без заметных изменений пять веков, но и перешагнул в электронный дизайн. Его популяризации в новое время послужили публикация листов Letraset с образцами Lorem Ipsum в 60-х годах и, в более недавнее время, программы электронной вёрстки типа Aldus PageMaker, в шаблонах которых используется Lorem Ipsum.
        </p>
      </div>
    </div>
  </div>
</main>

<p>
<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>