config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :steps
  devise_for :users, controllers:{
      sessions: 'users/sessions'
  }
  resources :portfolios
  resources :blogs
  resources :sites
  scope '/cabinet' do
    resources :messages, :orders
  end
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'page/index'
  root 'page#index'
  match '/contact', to: 'page#contact', via: [:get]
  match '/service', to: 'service#index', via: [:get]
  match '/service', to: 'service#create', via: [:post]
  match '/service/site', to: 'service#site', via: [:get]
  match '/service/dizajn', to: 'service#dizajn', via: [:get]
  match '/service/mobile', to: 'service#mobile', via: [:get]
  match '/service/business', to: 'service#business', via: [:get]
  resources :blog, :case
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_attached_file :image, styles: { large: "1920x1280", small: "300x200"}, default_url: "/images/:style/missing.png"
  validates :name, presence: true
  validates :tag, presence: true
  validates :annotation, presence: true,length: {maximum:290}
  validates :description, presence: true
  validates_attachment :image, presence: true,
                       content_type: { content_type: ["image/jpeg", "image/png", "image/jpg"] },
                       size: { in: 0..2.megabytes }
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :order
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :messages
  has_many :steps
  has_many :documents
  validates :user_name, presence: true
  validates :user_email, presence: true
  validates :user_phone, presence: true
  validates :user_password, confirmation: true
  validates :user_password_confirmation, presence: true
  validates :user_name, presence: true

end

app/models/page.rb
class Page < ApplicationRecord
  #attr_accessible :page_title, :description, :keywords
 #validates :page_title, :description, :keywords
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_attached_file :image, styles: { large: "1920x1280", small: "330x650"}, default_url: "/images/:style/missing.png"
  validates :title, presence: true
  validates :tag, presence: true
  validates :annotation, presence: true
  validates_attachment :image, presence: true,
                       content_type: { content_type: ["image/jpeg", "image/png", "image/jpg"] },
                       size: { in: 0..2.megabytes }
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/site.rb
class Site < ApplicationRecord
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable and :omniauthable
  has_many :orders, dependent: :destroy
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/_contactform.erb
<div class="screen" id="screen_forma">
  <h2>Обратная связь</h2>
  <div class="wrap">
    <form action="#" class="form">
      <input type="text" placeholder="Дурашка">
      <input type="tel" placeholder="Телефон">
      <input type="email" placeholder="E-mail">
      <textarea>Суть вопроса...</textarea>
      <button type="submit">Отправить запрос</button>
    </form>
  </div>
</div>

app/views/layouts/_crm_nav.erb
<ul class="crm_nav">
  <li><%= link_to "Описание", orders_url %></li>
  <li><%= link_to "Диалог", messages_url %></li>
  <li><a href="srm_settings.html">Настройки</a></li>
  <li><a href="srm_notif.html">Оповещения</a></li>
</ul>

app/views/layouts/_order_detail.erb
<div id="screen_form">
  <div class="wrap">
    <div class="form_calc">
      <p>Имя:</p>
      <input type="text" name="order[user_name]">
      <p>E-mail:</p>
      <input type="email" name="order[user_email]">
      <p>Телефон:</p>
      <input type="tel" name="order[user_phone]">
      <p>Пароль:</p>
      <input type="password" name="order[user_password]">
      <p>Подтверждение пароля:</p>
      <input type="password" name="order[user_password_confirmation]">
      <p>Название заказа:</p>
      <input type="text" name="order[order_title]">
      <p>Описание задания:</p>
      <textarea name="order[order_detail]"></textarea>
      <div class="calc_price sticky">Цена: <span id="total_calc">Не выбрана</span></div>
      <button name="button" type="submit" class="calc_btn">Отправить заказ</button>
    </div>
  </div>
</div>

app/views/layouts/_order_detail2.erb
<div id="screen_form">
  <div class="wrap">
    <div class="form_calc">
      <p>Имя:</p>
      <input type="text" name="order[user_name]">
      <p>E-mail:</p>
      <input type="email" name="order[user_email]">
      <p>Телефон:</p>
      <input type="tel" name="order[user_phone]">
      <p>Пароль:</p>
      <input type="password" name="order[user_password]">
      <p>Подтверждение пароля:</p>
      <input type="password" name="order[user_password_confirmation]">
      <p>Название заказа:</p>
      <input type="text" name="order[order_title]">
      <p>Описание задания:</p>
      <textarea name="order[order_detail]"></textarea>
      <button name="button" type="submit" class="calc_btn">Отправить заказ</button>
    </div>
  </div>
</div>

app/views/layouts/_services.erb
<div class="screen" id="screen_services">
  <div>
    <a href="service/site" class="services" id="comp">
      <%= image_tag "icon/computer1.png"%>
      <span>Создание сайтов</span>
    </a>
  </div>
  <div>
    <a href="service/mobile" class="services">
      <%= image_tag "icon/smartphone2.png"%>
      <span id="razmob">Разработка мобильных приложений</span>
    </a>
  </div>
  <div>
    <a href="service/dizajn" class="services">
      <%= image_tag "icon/paint-board-and-brush1.png"%>
      <span id="grafdiz">Графический дизайн</span>
    </a>
  </div>
  <div>
    <a href="service/business" class="services">
      <%= image_tag "icon/bussinesssymbol1.png"%>
      <span id="buicn">Разработка приложений для бизнеса</span>
    </a>
  </div>
</div>
<div class="screen" id="screen_tehnology">
  <h2>Технологии которыми мы владеем</h2>
  <div class="tehnology">
    <div id="css"></div>
    <div id="htmlsp"></div>
    <div id="jssp"></div>
    <div id="rails"></div>
    <div id="java"></div>
  </div>
  <div class="tehnology">
    <div id="angular"></div>
    <div id=modx></div>
    <div id="swift"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= metamagic site: "Компания Levup", title: -> { meta_title_for(title, site) }
  %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <%= favicon_link_tag 'fav.png' %>
</head>
<body>
<%= render 'layouts/header'%>
<%= yield %>
<%= render 'layouts/footer'%>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/page/index.html.erb
<%
  meta title: "Главная страница",
       description: "Digital услуги продающих решений. Разработка сайтов, мобильных и бизнес приложений. LevUP Company - всегда на уровень Выше",
       keywords: "Разработка cайтов, разработка мобильных приложений, приложения для бизнеса"
%>

<main>
  <div class="screen" id="screen1">
    <%= image_tag "biglogo.png", :class => "biglogo" %>
    <h1>LevUp company - всегда на уровень выше</h1>
    <a href="#screen23" class="screen1_a" id="screen23">
      <%= image_tag "mouse.png" %>
    </a>
  </div>
  <div class="screen" id="screen_about">
    <div class="wrap">
      <h2>О Нас</h2>
      <p>    Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без заметных изменений пять веков, но и перешагнул в электронный дизайн. Его популяризации в новое время послужили публикация листов Letraset с образцами Lorem Ipsum в 60-х годах и, в более недавнее время, программы электронной вёрстки типа Aldus PageMaker, в шаблонах которых используется Lorem Ipsum.</p>
      <p id="ts">Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без заметных изменений пять веков, но и перешагнул в электронный дизайн. Его популяризации в новое время послужили публикация листов Letraset с образцами Lorem Ipsum в 60-х годах и, в более недавнее время, программы электронной вёрстки типа Aldus PageMaker, в шаблонах которых используется Lorem Ipsum.</p>
    </div>
  </div>
  <%= render 'layouts/services'%>
  <div class="screen" id="screen_advantages">
    <div class="wrap">
      <div class="advantages_wrap">
        <div class="advantages_wrap__item">
          <div id="brain"><span>Расширенный кругозор</span></div>
          <div class="advantages_wrap__item__info">
          </div>
        </div>
        <div class="advantages_wrap__item">
          <div id="clock"><span>Real time</span></div>
          <div class="advantages_wrap__item__info">
          </div>
        </div>
        <div class="advantages_wrap__item">
          <div id="eye"><span>Все на виду</span></div>
          <div class="advantages_wrap__item__info"></div>
        </div>
        <div class="advantages_wrap__item">
          <div id="spread">
            <span>Комплексная разработка</span>
          </div>
          <div class="advantages_wrap__item__info"></div>
        </div>
        <div class="advantages_wrap__item">
          <div id="grow">
            <span>Цена - качество</span>
          </div>
          <div class="advantages_wrap__item__info"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="screen" id="screen_zakaz">
    <a href="#ts"><button>Заказать услугу</button></a>
  </div>
  <%= render "layouts/contactform" %>
  <div class="screen" id="screen_blog">
    <div class="wrap">
      <h2>Блог</h2>
      <div class="blog_wrap">
        <a href="#" class="blog_wrap__item">
          <div class="blog_item__top">
            <h3>Бухенвальд как причина сербский войн</h3>
            <p>Разбераем бухенвальди какого хуя<br>ему надо</p>
          </div>
        </a>
        <a href="#" class="blog_wrap__item">
          <div class="blog_item__top">
            <h3>Бухенвальд как причина сербский войн</h3>
            <p>Разбераем бухенвальди какого хуя<br>ему надо</p>
          </div>
        </a>
        <a href="#" class="blog_wrap__item">
          <div class="blog_item__top">
            <h3>Бухенвальд как причина сербский войн</h3>
            <p>Разбераем бухенвальди какого хуя<br>ему надо</p>
          </div>
        </a>
      </div>
    </div>
  </div>
</main>